// <auto-generated />
namespace LibraryAp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class HAVE2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HAVE2));
        
        string IMigrationMetadata.Id
        {
            get { return "201809060216460_HAVE2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
