// <auto-generated />
namespace LibraryAp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class HAVE : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HAVE));
        
        string IMigrationMetadata.Id
        {
            get { return "201809052204013_HAVE"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
